//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PH_CT_PhieuDat
    {
        public string MaCT_PhieuDat { get; set; }
        public string MaLoaiHang { get; set; }
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public string MaHinhAnh { get; set; }
        public string MaPhieuDH { get; set; }
        public string MaMau { get; set; }
        public string MaSize { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> SoLuongHangDat { get; set; }
        public Nullable<decimal> DonGiaDat { get; set; }
    }
}
